# Generated by Django 5.2.1 on 2025-05-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('CPU', 'CPU'), ('RAM', 'RAM'), ('MOTHERBOARD', 'Motherboard'), ('STORAGE', 'Storage'), ('NIC', 'Network Interface Card'), ('PSU', 'Power Supply Unit'), ('CASE', 'Case'), ('OTHER', 'Other')], max_length=20)),
                ('model', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_justification', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(help_text='Size in rack units (U)')),
                ('components', models.ManyToManyField(blank=True, related_name='systems', to='server_deployments.component')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='server_deployments.rack')),
            ],
        ),
    ]
