# Generated by Django 5.2.1 on 2025-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='wattage',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
