# Generated by Django 5.2.1 on 2025-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0002_cpu_wattage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='model',
        ),
        migrations.AddField(
            model_name='ram',
            name='qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
