# Generated by Django 5.2.1 on 2025-05-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0003_remove_ram_model_ram_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('rpm', models.PositiveIntegerField(blank=True, null=True)),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='system',
            name='os_use_case',
        ),
        migrations.AddField(
            model_name='system',
            name='storage_devices',
            field=models.ManyToManyField(blank=True, to='server_deployments.storagedevice'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_deployments.storagetype'),
        ),
    ]
