# Generated by Django 5.2.1 on 2025-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0005_remove_storagedevice_storage_type_storagedevice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ram_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
