# Generated by Django 5.2.1 on 2025-05-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0006_system_ram_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='system',
            name='nic',
        ),
        migrations.RemoveField(
            model_name='system',
            name='ram',
        ),
        migrations.AddField(
            model_name='system',
            name='nic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_deployments.nic'),
        ),
        migrations.AddField(
            model_name='system',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_deployments.ram'),
        ),
    ]
