# Generated by Django 5.2.1 on 2025-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0007_remove_ram_qty_remove_system_nic_remove_system_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='role',
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
