# Generated by Django 5.2.1 on 2025-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0008_remove_system_role_storagedevice_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagedevice',
            name='type',
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe', 'NVMe')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
