# Generated by Django 5.2.1 on 2025-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0009_remove_storagedevice_type_storagedevice_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='rack_units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
