# Generated by Django 5.2.1 on 2025-06-02 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0010_system_rack_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
                ('file_count', models.IntegerField()),
                ('folder_size_bytes', models.BigIntegerField()),
                ('last_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_indexes', to='server_deployments.system')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
                ('season_count', models.IntegerField()),
                ('total_size_bytes', models.BigIntegerField()),
                ('last_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_show_indexes', to='server_deployments.system')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
                ('file_count', models.IntegerField()),
                ('folder_size_bytes', models.BigIntegerField()),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='server_deployments.tvshowindex')),
            ],
        ),
    ]
