# Generated by Django 5.2.1 on 2025-06-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0012_mediafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='storagedevice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='system',
            name='notes',
        ),
    ]
