# Generated by Django 5.2.1 on 2025-06-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0013_remove_case_notes_remove_cpu_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('internal_connectors', models.IntegerField()),
                ('external_connectors', models.IntegerField()),
                ('connectors', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('owned', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nic',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psu',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='owned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
