# Generated by Django 5.2.1 on 2025-06-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0014_hba_case_owned_cpu_owned_motherboard_owned_nic_owned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hba',
            old_name='connectors',
            new_name='connector_type',
        ),
    ]
