# Generated by Django 5.2.1 on 2025-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0016_convert_gb_to_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('cores', models.PositiveIntegerField()),
                ('vram', models.PositiveIntegerField()),
                ('vram_type', models.CharField(max_length=64)),
                ('bus_width', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('owned', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movieindex',
            name='system',
        ),
        migrations.RemoveField(
            model_name='seasonindex',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='tvshowindex',
            name='system',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.DeleteModel(
            name='MovieIndex',
        ),
        migrations.DeleteModel(
            name='SeasonIndex',
        ),
        migrations.DeleteModel(
            name='TVShowIndex',
        ),
    ]
