# Generated by Django 5.2.1 on 2025-06-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0017_gpu_remove_movieindex_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_deployments.system')),
            ],
        ),
        migrations.CreateModel(
            name='IndexedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField(unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_deployments.system')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='server_deployments.indexedfolder')),
            ],
        ),
    ]
