# Generated by Django 5.2.1 on 2025-06-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0019_indexedfolder_total_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
