# Generated by Django 5.2.1 on 2025-06-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0020_alter_indexedfile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagedevice',
            name='link',
        ),
        migrations.RemoveField(
            model_name='storagedevice',
            name='price_each',
        ),
    ]
