# Generated by Django 5.2.1 on 2025-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0021_remove_storagedevice_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='disk_location',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='failure',
            field=models.BooleanField(default=False),
        ),
    ]
