# Generated by Django 5.2.2 on 2025-09-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0022_storagedevice_disk_location_storagedevice_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='parity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='storage_sub_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
