# Generated by Django 5.2.1 on 2025-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0022_storagedevice_disk_location_storagedevice_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='pool',
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
    ]
