# Generated by Django 5.2.2 on 2025-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0023_storagedevice_cache_storagedevice_parity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='actual_fragmentation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='fragmentation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fragmentation percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='ideal_fragmentation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='utilisation',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of drive used', max_digits=5),
        ),
    ]
