# Generated by Django 5.2.2 on 2025-09-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0024_storagedevice_actual_fragmentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexedfolder',
            name='system',
        ),
        migrations.DeleteModel(
            name='IndexedFile',
        ),
        migrations.DeleteModel(
            name='IndexedFolder',
        ),
    ]
