# Generated by Django 5.2.6 on 2025-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0025_remove_indexedfolder_system_delete_indexedfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedevice',
            old_name='disk_location',
            new_name='disk_number',
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='disk_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
