# Generated by Django 5.2.6 on 2025-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0026_rename_disk_location_storagedevice_disk_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='fragmentation_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time fragmentation data was updated', null=True),
        ),
    ]
