# Generated by Django 5.2.6 on 2025-12-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0027_storagedevice_fragmentation_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='free_space_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Free space in GB', null=True),
        ),
    ]
