# Generated by Django 5.2.1 on 2026-02-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0028_storagedevice_free_space_gb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DjangoStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Content in HTML format')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the guide')),
                ('step_type', models.CharField(choices=[('section', 'Section'), ('command', 'Command'), ('code', 'Code Block'), ('note', 'Note')], default='section', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='server_deployments.djangoguide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
