# Generated by Django 3.2.21 on 2026-04-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0023_storagedevice_pool'),
        ('server_deployments', '0029_djangoguide_djangostep'),
    ]

    operations = [
    ]
