# Generated by Django 3.2.21 on 2026-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0030_merge_20260407_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the link', max_length=255)),
                ('url', models.URLField(help_text='URL to navigate to')),
                ('icon', models.CharField(blank=True, help_text='Icon filename or path', max_length=255)),
                ('category', models.CharField(choices=[('network', 'Network'), ('unraid', 'UNRAID'), ('servers', 'Servers'), ('docker', 'Docker'), ('services', 'Services'), ('monitoring', 'Monitoring'), ('other', 'Other')], default='other', help_text='Category for grouping links', max_length=50)),
                ('tab', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('public', 'Public')], default='internal', help_text='Which dashboard tab to show this link on', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Additional description (e.g., IP address)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('active', models.BooleanField(default=True, help_text='Whether to display this link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tab', 'category', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='storagedevice',
            name='pool',
        ),
    ]
