# Generated by Django 3.2.21 on 2026-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_deployments', '0031_auto_20260407_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlink',
            name='tab',
            field=models.CharField(choices=[('network', 'Network'), ('apps', 'Apps'), ('public', 'Public')], default='network', help_text='Which dashboard tab to show this link on', max_length=20),
        ),
    ]
